camera_node:
  ros__parameters:
    image_topic: "/image_raw"
    min_contour_area: 500.0

    # Red (split range in HSV)
    h_min_red1: 0
    s_min_red1: 120
    v_min_red1: 70
    h_max_red1: 10
    s_max_red1: 255
    v_max_red1: 255
    h_min_red2: 170
    s_min_red2: 120
    v_min_red2: 70
    h_max_red2: 180
    s_max_red2: 255
    v_max_red2: 255
    # Yellow
    h_min_yellow: 20
    s_min_yellow: 100
    v_min_yellow: 100
    h_max_yellow: 30
    s_max_yellow: 255
    v_max_yellow: 255
    # Blue
    h_min_blue: 90
    s_min_blue: 80
    v_min_blue: 80
    h_max_blue: 130
    s_max_blue: 255
    v_max_blue: 255