# Camera intrinsic parameters (example)
camera_matrix:
  rows: 3
  cols: 3
  data: [fx, 0, cx, 0, fy, cy, 0, 0, 1]

distortion_coefficients:
  rows: 1
  cols: 5
  data: [k1, k2, p1, p2, k3]

# HSV color thresholds for cube detection
color_detector:
  ros__parameters:
    red.hue_low: 0
    red.hue_high: 10
    red.sat_low: 100
    red.sat_high: 255
    red.val_low: 100
    red.val_high: 255

    yellow.hue_low: 20
    yellow.hue_high: 30
    yellow.sat_low: 100
    yellow.sat_high: 255
    yellow.val_low: 100
    yellow.val_high: 255

    blue.hue_low: 100
    blue.hue_high: 130
    blue.sat_low: 100
    blue.sat_high: 255
    blue.val_low: 100
    blue.val_high: 255


# Other camera related parameters
image_topic: "/camera/color/image_raw"
camera_info_topic: "/camera/color/camera_info"
