task_manager:
  ros__parameters:
    home_position:
      frame_id: "base_link"
      position:
        x: -0.253
        y: 0.44
        z: 0.49
      orientation:
        x: 0.38
        y: 0.92
        z: -0.00001
        w: -0.00005